# Generated by Django 5.0.3 on 2024-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='fundamentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='metodologia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
